// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Auspex.Control.Data;

#nullable disable

namespace Auspex.Control.Data.Migrations
{
    [DbContext(typeof(AnalyticsDbContext))]
    [Migration("20260822173716_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Auspex.Control.Data.Finding", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Client")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detector")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Dismissed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double>("Score")
                        .HasColumnType("REAL");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .HasMaxLength(253)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("WindowEndUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("WindowStartUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Fingerprint")
                        .IsUnique();

                    b.HasIndex("Dismissed", "DetectedUtc");

                    b.ToTable("Findings");
                });

            modelBuilder.Entity("Auspex.Control.Data.IngestState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Boot")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("Ingested")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastRunUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("LastSeq")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LostTotal")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("IngestStates");
                });

            modelBuilder.Entity("Auspex.Control.Data.QueryRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Boot")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Client")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("List")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("LongestLabel")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Millis")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("TEXT");

                    b.Property<string>("Profile")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rcode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rule")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Schedule")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("Seq")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Upstream")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TimeUtc");

                    b.HasIndex("Action", "TimeUtc");

                    b.HasIndex("Boot", "Seq")
                        .IsUnique();

                    b.HasIndex("Client", "TimeUtc");

                    b.HasIndex("Domain", "TimeUtc");

                    b.ToTable("Queries");
                });
#pragma warning restore 612, 618
        }
    }
}
